// HR Codex State Compliance Data
// Published by HR Codex — Professional HR Compliance Resources

export const FEDERAL_QUESTIONS = [
  { id:"f1", cat:"wage", text:"Do you pay all non-exempt employees at least the federal minimum wage of $7.25/hour?", weight:3, critical:true, freeDetail:true, detail:"The Fair Labor Standards Act (FLSA) requires a minimum wage of $7.25/hr for all covered non-exempt employees. Many states set higher minimums that supersede this." },
  { id:"f2", cat:"wage", text:"Do you pay overtime at 1.5x the regular rate for hours exceeding 40 in a workweek for non-exempt employees?", weight:3, critical:true, freeDetail:true, detail:"FLSA mandates overtime pay at one-and-a-half times the regular rate for all hours worked over 40 in a single workweek. Some states have additional daily overtime rules." },
  { id:"f3", cat:"wage", text:"Have you correctly classified all employees as exempt or non-exempt under FLSA?", weight:3, critical:true, freeDetail:false, detail:"Misclassification is one of the most common and costly FLSA violations. Exempt employees must meet both the salary threshold ($58,656/year as of 2026) and duties tests for executive, administrative, professional, or outside sales exemptions." },
  { id:"f4", cat:"wage", text:"Do you maintain accurate time records for all non-exempt employees?", weight:2, critical:true, freeDetail:false, detail:"FLSA requires employers to keep accurate records of hours worked and wages paid for all non-exempt employees. Records must be preserved for at least 3 years for payroll records and 2 years for time cards." },
  { id:"f5", cat:"hire", text:"Do you complete Form I-9 for every new hire within 3 business days of their start date?", weight:3, critical:true, freeDetail:true, detail:"Federal law requires employers to verify the identity and employment authorization of every employee hired. Section 1 must be completed by the employee on or before the first day of work. Section 2 must be completed by the employer within 3 business days." },
  { id:"f6", cat:"hire", text:"Do you report all new hires to your state's New Hire Reporting Program within 20 days?", weight:2, critical:false, freeDetail:false, detail:"Federal law requires employers to report new hires (and rehires) to the state directory within 20 days of the hire date. This supports child support enforcement. Most states require the same or shorter timeframe." },
  { id:"f7", cat:"hire", text:"Do you display all required federal workplace posters in a conspicuous location?", weight:2, critical:false, freeDetail:true, detail:"Employers must display posters informing employees of their rights under FLSA, OSHA, FMLA, EEO, EPPA, and USERRA. Failure to post can result in fines up to $15,000+ per violation depending on the poster." },
  { id:"f8", cat:"leave", text:"If you have 50+ employees, do you provide up to 12 weeks of unpaid, job-protected leave under FMLA?", weight:3, critical:true, freeDetail:false, detail:"The Family and Medical Leave Act requires covered employers (50+ employees within 75 miles) to provide 12 weeks of unpaid leave for qualifying reasons including birth/adoption, serious health condition, or military family leave. Employees must have worked 12 months and 1,250 hours to be eligible." },
  { id:"f9", cat:"leave", text:"Do you continue group health insurance coverage during FMLA leave on the same terms as active employment?", weight:2, critical:true, freeDetail:false, detail:"During FMLA leave, employers must maintain the employee's group health insurance coverage under the same conditions as if the employee had continued working." },
  { id:"f10", cat:"leave", text:"Do you offer COBRA continuation coverage to eligible employees who lose group health coverage?", weight:2, critical:false, freeDetail:false, detail:"Employers with 20+ employees offering group health plans must provide COBRA continuation coverage for up to 18 months (36 in some cases) when coverage would otherwise end due to qualifying events like termination or reduced hours." },
  { id:"f11", cat:"safety", text:"Do you maintain a workplace free from recognized hazards as required by OSHA?", weight:3, critical:true, freeDetail:true, detail:"The General Duty Clause of the Occupational Safety and Health Act requires every employer to provide a workplace free from recognized hazards that are causing or likely to cause death or serious physical harm." },
  { id:"f12", cat:"safety", text:"Do you maintain OSHA 300 logs if you have 10+ employees (and are not in an exempt industry)?", weight:2, critical:false, freeDetail:false, detail:"Employers with 10+ employees must maintain OSHA Form 300 (Log of Work-Related Injuries and Illnesses), Form 300A (Summary), and Form 301 (Incident Report). Certain low-hazard industries are exempt from routine recordkeeping." },
  { id:"f13", cat:"safety", text:"Do you have workers compensation insurance or a qualified self-insurance program?", weight:3, critical:true, freeDetail:false, detail:"While workers compensation is administered at the state level, nearly all states require employers to carry coverage. Failure to maintain coverage can result in criminal penalties, civil fines, and personal liability for workplace injuries." },
  { id:"f14", cat:"disc", text:"Do you comply with Title VII prohibitions against discrimination based on race, color, religion, sex, or national origin?", weight:3, critical:true, freeDetail:true, detail:"Title VII of the Civil Rights Act applies to employers with 15+ employees and prohibits discrimination in hiring, firing, compensation, and all terms and conditions of employment based on protected characteristics." },
  { id:"f15", cat:"disc", text:"Do you provide reasonable accommodations for qualified individuals with disabilities under the ADA?", weight:3, critical:true, freeDetail:false, detail:"The Americans with Disabilities Act requires employers with 15+ employees to provide reasonable accommodations unless doing so would cause undue hardship. This includes modifying work schedules, equipment, policies, or physical workspace." },
  { id:"f16", cat:"disc", text:"Do you comply with ADEA protections for employees and applicants age 40 and older?", weight:2, critical:false, freeDetail:false, detail:"The Age Discrimination in Employment Act protects individuals 40+ from employment discrimination. It applies to employers with 20+ employees and covers hiring, firing, pay, job assignments, promotions, training, and benefits." },
  { id:"f17", cat:"disc", text:"Do you have a written anti-harassment policy and complaint procedure?", weight:2, critical:true, freeDetail:false, detail:"While not explicitly required by federal statute, the Supreme Court established in Faragher v. City of Boca Raton that having a written anti-harassment policy with a complaint procedure is an affirmative defense to harassment claims. Practically, it is essential." },
  { id:"f18", cat:"disc", text:"Do you pay men and women equally for substantially equal work as required by the Equal Pay Act?", weight:3, critical:true, freeDetail:false, detail:"The Equal Pay Act requires equal pay for men and women performing substantially equal work in the same establishment. Pay differentials are allowed only based on seniority, merit, quantity/quality of production, or any factor other than sex." },
  { id:"f19", cat:"term", text:"Do you provide WARN Act notice (60 days) before mass layoffs or plant closings affecting 50+ employees?", weight:2, critical:true, freeDetail:false, detail:"The Worker Adjustment and Retraining Notification Act requires employers with 100+ employees to provide 60 calendar days advance written notice of plant closings or mass layoffs affecting 50+ employees. Several states have stricter mini-WARN acts." },
  { id:"f20", cat:"term", text:"Do you have a consistent, documented termination process that includes reason for termination?", weight:2, critical:false, freeDetail:true, detail:"While at-will employment allows termination for any lawful reason, maintaining documentation of the reason for termination is essential for defending against wrongful termination, discrimination, or retaliation claims." },
  { id:"f21", cat:"term", text:"Do you protect employees from retaliation for filing complaints, participating in investigations, or exercising legal rights?", weight:3, critical:true, freeDetail:false, detail:"Multiple federal laws (Title VII, FLSA, OSHA, FMLA, ADA, SOX) prohibit retaliation against employees who exercise their rights. Retaliation claims are the most frequently filed charge with the EEOC." },
  { id:"f22", cat:"leave", text:"Do you provide job-protected leave for employees called to military service under USERRA?", weight:2, critical:false, freeDetail:false, detail:"The Uniformed Services Employment and Reemployment Rights Act protects employees who leave civilian jobs for military service. Returning service members must be reemployed in the position they would have held had they remained continuously employed." },
];

export const STATE_DATA = {
  TX: {
    name: "Texas", code: "TX",
    tagline: "The Lone Star Compliance Check",
    minWage: "$7.25 (federal)",
    updated: "2026-01-15",
    questions: [
      { id:"tx1", cat:"wage", text:"Are you aware that Texas follows the federal minimum wage of $7.25/hour with no state minimum?", weight:1, critical:false, freeDetail:true, detail:"Texas does not have a state minimum wage above the federal rate. The Texas Minimum Wage Act defers to the FLSA rate of $7.25/hr. Some cities have attempted higher minimums but Texas preempts local wage ordinances." },
      { id:"tx2", cat:"wage", text:"Do you pay all wages owed to employees on the designated paydays at least twice per month?", weight:2, critical:true, freeDetail:false, detail:"The Texas Payday Law requires employers to pay employees on regularly scheduled paydays at least twice per month for non-exempt employees. Exempt employees may be paid once per month. Failure to pay wages on time can result in penalties up to the amount of wages claimed." },
      { id:"tx3", cat:"wage", text:"Do you provide a written earnings statement (pay stub) to each employee with each payment of wages?", weight:1, critical:false, freeDetail:false, detail:"Texas Payday Law requires employers to provide a written earnings statement with each wage payment showing hours worked, rate of pay, deductions, and net pay." },
      { id:"tx4", cat:"hire", text:"Do you use E-Verify if you are a state contractor or subcontractor?", weight:2, critical:false, freeDetail:false, detail:"Texas law (HB 1683) requires all state agencies and political subdivisions to use E-Verify for new hires. Private employers contracting with the state must also use E-Verify. It is not yet mandatory for all private employers." },
      { id:"tx5", cat:"hire", text:"Do you report new hires to the Texas Attorney General's office within 20 days?", weight:2, critical:false, freeDetail:false, detail:"Texas requires new hire reporting within 20 days of the hire date. Reports go to the Texas Attorney General's New Hire Reporting Program and must include employee name, address, SSN, date of hire, and employer information." },
      { id:"tx6", cat:"leave", text:"If you have 15+ employees, do you allow up to 10 days of unpaid leave for employees who are victims of family violence?", weight:2, critical:false, freeDetail:false, detail:"Texas law provides that employees of companies with 15+ employees may take unpaid leave for family violence situations, including seeking medical attention, legal assistance, or relocation." },
      { id:"tx7", cat:"safety", text:"Are you aware that Texas workers compensation insurance is voluntary (not mandatory)?", weight:3, critical:true, freeDetail:true, detail:"Texas is the only state where workers compensation is truly voluntary for private employers. However, non-subscribers lose key legal defenses if an employee is injured — they cannot argue contributory negligence, fellow employee negligence, or assumption of risk. Most employers carry coverage due to this significant liability exposure." },
      { id:"tx8", cat:"safety", text:"If you are a non-subscriber to workers comp, do you provide required notice to employees and file with the DWC?", weight:2, critical:true, freeDetail:false, detail:"Non-subscribing employers must file DWC Form-005 with the Texas Division of Workers Compensation annually and post notice in the workplace that they do not carry workers comp. They must also notify new hires in writing." },
      { id:"tx9", cat:"disc", text:"Do you comply with the Texas Commission on Human Rights Act (Texas Labor Code Chapter 21)?", weight:3, critical:true, freeDetail:false, detail:"The Texas Labor Code prohibits employment discrimination based on race, color, disability, religion, sex, national origin, age (40+), and genetic information. It applies to employers with 15+ employees and mirrors many federal Title VII protections." },
      { id:"tx10", cat:"disc", text:"If you have 25+ employees, do you provide sexual harassment prevention training?", weight:2, critical:false, freeDetail:false, detail:"Texas requires state agencies and state contractors with 25+ employees to provide sexual harassment prevention training to all employees. While not mandatory for all private employers, it is strongly recommended as an affirmative defense." },
      { id:"tx11", cat:"term", text:"Do you pay a terminated employee's final wages within 6 calendar days of termination?", weight:3, critical:true, freeDetail:true, detail:"Under the Texas Payday Law, if an employer discharges an employee, final wages are due within 6 calendar days. If the employee quits, final wages are due on the next regularly scheduled payday. There is no requirement to pay out accrued vacation unless the employer's policy or agreement provides for it." },
      { id:"tx12", cat:"term", text:"Are you aware that Texas is an at-will employment state with limited exceptions?", weight:1, critical:false, freeDetail:true, detail:"Texas is an at-will state, meaning employment can be terminated by either party at any time for any lawful reason. Exceptions include termination based on protected class status, retaliation for filing a workers comp claim, jury duty, or military service." },
      { id:"tx13", cat:"hire", text:"Do your job applications avoid asking about criminal history before a conditional offer (if applicable)?", weight:1, critical:false, freeDetail:false, detail:"While Texas does not have a statewide ban-the-box law, several Texas cities including Austin have fair chance hiring ordinances restricting when criminal history can be inquired about. Federal contractors are also subject to EEOC guidance on criminal background checks." },
      { id:"tx14", cat:"wage", text:"Do you ensure that tipped employees earn at least $7.25/hour when combining the $2.13 cash wage plus tips?", weight:2, critical:true, freeDetail:false, detail:"Texas follows the federal tip credit provisions. Employers may pay tipped employees $2.13/hour cash wage if tips bring total compensation to at least $7.25/hour. If tips fall short, the employer must make up the difference." },
      { id:"tx15", cat:"safety", text:"Do you report workplace fatalities to OSHA within 8 hours and serious injuries within 24 hours?", weight:3, critical:true, freeDetail:false, detail:"Texas employers must report any workplace fatality within 8 hours and any inpatient hospitalization, amputation, or loss of an eye within 24 hours. Texas does not have its own state OSHA plan — federal OSHA has jurisdiction." },
    ]
  },
  CA: {
    name: "California", code: "CA",
    tagline: "Golden State Compliance Check",
    minWage: "$16.50/hr (2026)",
    updated: "2026-01-15",
    questions: [
      { id:"ca1", cat:"wage", text:"Do you pay all employees at least California's minimum wage of $16.50/hour (2026)?", weight:3, critical:true, freeDetail:true, detail:"California's statewide minimum wage is $16.50/hr as of January 2026. Many cities and counties have higher local minimums. Fast food workers have a $20/hr minimum. Healthcare workers have a phased-in $25/hr minimum." },
      { id:"ca2", cat:"wage", text:"Do you pay daily overtime (1.5x after 8 hours, 2x after 12 hours in a single day)?", weight:3, critical:true, freeDetail:true, detail:"California is one of few states requiring daily overtime. Non-exempt employees earn 1.5x for hours 8-12 in a day, and 2x for hours beyond 12. Seventh consecutive day in a workweek also triggers overtime after the first 8 hours." },
      { id:"ca3", cat:"wage", text:"Do you provide compliant meal periods (30 min for shifts over 5 hours) and rest breaks (10 min per 4 hours)?", weight:3, critical:true, freeDetail:false, detail:"California requires a 30-minute unpaid meal period for shifts over 5 hours (second meal for shifts over 10 hours) and paid 10-minute rest breaks for every 4 hours worked. Failure to provide these triggers premium pay of one hour at the regular rate per violation per day." },
      { id:"ca4", cat:"wage", text:"Do you provide itemized wage statements on each payday showing all required information?", weight:2, critical:true, freeDetail:false, detail:"California Labor Code Section 226 requires detailed pay stubs showing gross/net wages, hourly rates, hours worked, deductions, pay period dates, employer name/address, and employee name/last 4 of SSN. Penalties for non-compliant pay stubs can reach $4,000+ per employee." },
      { id:"ca5", cat:"hire", text:"Do you comply with California's ban on salary history inquiries during hiring?", weight:2, critical:false, freeDetail:false, detail:"California prohibits employers from asking about or relying on a job applicant's salary history. Employers must also provide the pay scale for a position upon reasonable request from an applicant." },
      { id:"ca6", cat:"hire", text:"Do you include pay ranges in all job postings as required by SB 1162?", weight:2, critical:true, freeDetail:true, detail:"California's pay transparency law requires employers with 15+ employees to include pay scale (salary or hourly range) in all job postings, including those posted by third parties. Non-compliance can result in penalties up to $10,000 per violation." },
      { id:"ca7", cat:"leave", text:"Do you provide California Paid Family Leave benefits information to employees?", weight:2, critical:false, freeDetail:false, detail:"California PFL provides up to 8 weeks of partial wage replacement for employees bonding with a new child or caring for a seriously ill family member. Benefits are funded through employee payroll deductions (SDI). Employers must provide notice of PFL rights." },
      { id:"ca8", cat:"leave", text:"Do you provide at least 5 days (40 hours) of paid sick leave annually?", weight:3, critical:true, freeDetail:false, detail:"As of 2024, California requires 5 days (40 hours) of paid sick leave per year, up from the previous 3 days. Employers can frontload or use an accrual method (1 hour per 30 hours worked). Many cities require additional local sick leave." },
      { id:"ca9", cat:"leave", text:"Do you comply with CFRA (California Family Rights Act) providing up to 12 weeks of job-protected leave for employers with 5+ employees?", weight:3, critical:true, freeDetail:false, detail:"CFRA applies to employers with just 5+ employees (much lower than FMLA's 50). It provides 12 weeks of unpaid, job-protected leave for bonding with a new child, caring for a family member with a serious health condition, or the employee's own serious health condition." },
      { id:"ca10", cat:"disc", text:"Are you compliant with California's FEHA protections, which cover more categories than federal law?", weight:3, critical:true, freeDetail:false, detail:"The Fair Employment and Housing Act (FEHA) prohibits discrimination and harassment based on more categories than federal law, including sexual orientation, gender identity, marital status, military/veteran status, and reproductive health decisions. FEHA applies to employers with 5+ employees." },
      { id:"ca11", cat:"disc", text:"Do you provide sexual harassment prevention training (2 hours for supervisors, 1 hour for non-supervisors) every two years?", weight:2, critical:true, freeDetail:false, detail:"Employers with 5+ employees must provide interactive sexual harassment prevention training to all employees within 6 months of hire and every 2 years. Supervisors require 2 hours; non-supervisory employees require 1 hour." },
      { id:"ca12", cat:"term", text:"Do you pay all final wages immediately upon involuntary termination?", weight:3, critical:true, freeDetail:true, detail:"California requires immediate payment of all wages due at the time of involuntary termination. For employees who quit with 72+ hours notice, final wages are due on the last day. For quits without notice, within 72 hours. Penalties for late payment: up to 30 days of waiting time penalties at the daily rate of pay." },
      { id:"ca13", cat:"term", text:"Are you compliant with California's ban on non-compete agreements (effective 2024)?", weight:3, critical:true, freeDetail:true, detail:"California broadly prohibits non-compete agreements. AB 1076 and SB 699 (effective 2024) reinforce that any non-compete clause is void regardless of where it was signed. Employers were required to notify current and former employees by February 14, 2024. Violations can result in legal action." },
      { id:"ca14", cat:"safety", text:"Do you maintain a written Injury and Illness Prevention Program (IIPP)?", weight:3, critical:true, freeDetail:false, detail:"California requires every employer to establish and maintain an effective written IIPP. This must include responsibility designation, compliance system, hazard communication, accident investigation procedures, hazard correction, and employee training. Cal/OSHA enforces this strictly." },
      { id:"ca15", cat:"hire", text:"Have you registered for and are you compliant with the CalSavers retirement savings program (if applicable)?", weight:2, critical:false, freeDetail:false, detail:"Employers with 1+ employees in California who do not offer a qualified retirement plan must register for CalSavers, a state-facilitated retirement savings program. Penalties for non-compliance start at $250 per employee after 90 days." },
    ]
  },
  NY: {
    name: "New York", code: "NY",
    tagline: "Empire State Compliance Check",
    minWage: "$17.00/hr NYC (2026)",
    updated: "2026-01-15",
    questions: [
      { id:"ny1", cat:"wage", text:"Do you pay at least New York's applicable minimum wage ($17/hr NYC, $16.50 Westchester/LI, $15.50 rest of state)?", weight:3, critical:true, freeDetail:true, detail:"New York has tiered minimum wages by region. As of 2026: NYC is $17/hr, Westchester County and Long Island are $16.50/hr, and the rest of the state is $15.50/hr. These rates are indexed to inflation going forward." },
      { id:"ny2", cat:"wage", text:"Do you comply with the NY HERO Act workplace safety committee requirements?", weight:2, critical:false, freeDetail:false, detail:"The NY HERO Act requires employers with 10+ employees to permit employees to establish joint labor-management workplace safety committees. Employers must also adopt an airborne infectious disease exposure prevention plan." },
      { id:"ny3", cat:"leave", text:"Do you provide New York Paid Family Leave (up to 12 weeks at 67% of average weekly wage)?", weight:3, critical:true, freeDetail:true, detail:"NYS PFL provides up to 12 weeks of job-protected paid leave at 67% of the employee's average weekly wage (capped at 67% of the state average weekly wage — $1,228.53/week in 2026). Funded through employee payroll deductions. Covers bonding, caregiving, and military family leave." },
      { id:"ny4", cat:"leave", text:"Do you provide paid sick leave as required by NYS (amount based on employer size)?", weight:3, critical:true, freeDetail:false, detail:"New York's paid sick leave law requires: 0-4 employees with net income over $1M — 40 hours paid sick leave; 5-99 employees — 40 hours paid; 100+ employees — 56 hours paid. NYC has additional requirements under the Earned Safe and Sick Time Act (ESSTA) providing up to 56 hours for employers with 5+ employees." },
      { id:"ny5", cat:"leave", text:"Do you provide short-term disability benefits through an approved plan?", weight:2, critical:true, freeDetail:false, detail:"New York requires employers to provide short-term disability benefits covering off-the-job injuries and illnesses. Benefits are 50% of the employee's average weekly wage, capped at $170/week, for up to 26 weeks. Coverage must be through an approved insurance carrier, self-insurance, or the State Insurance Fund." },
      { id:"ny6", cat:"hire", text:"Do you comply with New York's salary transparency law requiring pay ranges in job postings?", weight:2, critical:true, freeDetail:false, detail:"New York's pay transparency law requires employers with 4+ employees to disclose the compensation range (minimum and maximum annual salary or hourly rate) in any job advertisement. This applies to postings for jobs performed in New York." },
      { id:"ny7", cat:"hire", text:"Are you compliant with NYC's ban on automated employment decision tools (AEDT) without bias audits?", weight:2, critical:false, freeDetail:false, detail:"NYC Local Law 144 regulates the use of AI and automated tools in hiring decisions. Employers must conduct independent bias audits annually, publish audit results, and notify candidates that AEDT is being used. Non-compliance can result in fines of $500-$1,500 per violation." },
      { id:"ny8", cat:"disc", text:"Do you comply with the New York State Human Rights Law, which has no minimum employee threshold?", weight:3, critical:true, freeDetail:false, detail:"The NYSHRL applies to ALL employers regardless of size (no minimum employee count). It prohibits discrimination based on age, race, creed, color, national origin, sexual orientation, gender identity, military status, sex, disability, marital status, domestic violence victim status, and more." },
      { id:"ny9", cat:"disc", text:"Do you provide annual sexual harassment prevention training to all employees?", weight:2, critical:true, freeDetail:false, detail:"New York State requires ALL employers to provide annual interactive sexual harassment prevention training to all employees. The training must meet minimum standards set by the NYS Department of Labor and Division of Human Rights." },
      { id:"ny10", cat:"term", text:"Do you pay final wages by the next regular payday after termination?", weight:2, critical:true, freeDetail:false, detail:"New York requires payment of final wages no later than the next regular payday following termination. Unlike some states, there is no requirement for immediate payment upon involuntary termination. Manual workers who are terminated must be paid within the next regular payday." },
      { id:"ny11", cat:"term", text:"Do you provide the required written notice of termination to employees (WARN Act — 90 days for 50+ employees)?", weight:2, critical:false, freeDetail:false, detail:"New York's WARN Act is more protective than federal: applies to employers with 50+ employees (vs 100 federal), requires 90 days notice (vs 60 federal), and covers layoffs affecting 25+ employees. Penalties include back pay and benefits for each day of violation." },
      { id:"ny12", cat:"safety", text:"Do you carry workers compensation insurance as required for all New York employees?", weight:3, critical:true, freeDetail:false, detail:"New York mandates workers compensation for virtually all employees. There are very few exceptions. Failure to carry coverage is a criminal offense — misdemeanor for the first offense, felony for subsequent offenses. Fines range from $2,000 per 10-day period to $50,000." },
      { id:"ny13", cat:"hire", text:"Do you provide new hires with a written notice of pay rate, pay day, and other employment terms (Wage Theft Prevention Act)?", weight:2, critical:true, freeDetail:true, detail:"The NY Wage Theft Prevention Act requires employers to give new hires a written notice at the time of hiring specifying: rate of pay, overtime rate, pay day, employer name/address/phone, and allowances claimed against minimum wage. The notice must be in the employee's primary language." },
    ]
  },
  FL: {
    name: "Florida", code: "FL",
    tagline: "Sunshine State Compliance Check",
    minWage: "$14.00/hr (2026)",
    updated: "2026-01-15",
    questions: [
      { id:"fl1", cat:"wage", text:"Do you pay at least Florida's minimum wage of $14.00/hour (2026)?", weight:3, critical:true, freeDetail:true, detail:"Florida's minimum wage is $14.00/hr as of September 2026 per Amendment 2 (2020) which increases the rate $1/year until reaching $15 in September 2026. Tipped employees minimum cash wage is $10.98/hr." },
      { id:"fl2", cat:"hire", text:"Do you use E-Verify for all new hires (required for private employers with 25+ employees)?", weight:2, critical:true, freeDetail:true, detail:"Effective July 2023, Florida SB 1718 requires private employers with 25+ employees to use E-Verify for new hires. Employers must retain a copy of each verification for at least 3 years. Non-compliance can result in license suspension." },
      { id:"fl3", cat:"leave", text:"Are you aware that Florida has no state-mandated paid sick leave, FMLA-equivalent, or family leave law?", weight:1, critical:false, freeDetail:true, detail:"Florida does not require private employers to provide paid or unpaid sick leave, family leave, or medical leave beyond what federal law (FMLA) requires. Some Florida counties have attempted local sick leave ordinances but state preemption prevents enforcement." },
      { id:"fl4", cat:"disc", text:"Do you comply with the Florida Civil Rights Act (employers with 15+ employees)?", weight:3, critical:true, freeDetail:false, detail:"The Florida Civil Rights Act mirrors federal protections and applies to employers with 15+ employees. It prohibits discrimination based on race, color, religion, sex, pregnancy, national origin, age (40+), disability, marital status, and AIDS/HIV status." },
      { id:"fl5", cat:"term", text:"Do you pay terminated employees by the next regular payday or within a reasonable time?", weight:2, critical:false, freeDetail:false, detail:"Florida does not have a specific final paycheck law with defined timelines. Final wages are generally due by the next regular payday. Unpaid wages can be pursued under the FLSA or through civil action." },
      { id:"fl6", cat:"safety", text:"Do you carry workers compensation for employers with 4+ employees (or 1+ in construction)?", weight:3, critical:true, freeDetail:false, detail:"Florida requires workers compensation for employers with 4+ regular employees (1+ for construction, all for agricultural employers with 6+ regular or 12+ seasonal workers). Non-compliance is a criminal offense and stop-work orders can be issued." },
      { id:"fl7", cat:"disc", text:"Are you aware of Florida's new restrictions on diversity, equity, and inclusion workplace training?", weight:1, critical:false, freeDetail:false, detail:"Florida's Individual Freedom Act (Stop WOKE Act) restricts certain DEI training topics in the workplace. Employers cannot require training that asserts individuals are inherently privileged or oppressed based on race or sex. Portions of this law have faced legal challenges." },
      { id:"fl8", cat:"hire", text:"Do you comply with Florida's drug-free workplace requirements if you participate in the program for workers comp premium discounts?", weight:1, critical:false, freeDetail:false, detail:"Florida's Drug-Free Workplace Act provides a 5% workers compensation premium discount for employers who implement a qualifying drug-free workplace program including written policy, employee education, supervisor training, EAP, and testing protocols." },
      { id:"fl9", cat:"wage", text:"Do you display the Florida Minimum Wage poster in a conspicuous place at the worksite?", weight:1, critical:false, freeDetail:false, detail:"Florida employers must display the official Florida Minimum Wage poster in a conspicuous location accessible to all employees. The poster must be updated annually when the minimum wage changes." },
      { id:"fl10", cat:"term", text:"Are you aware that Florida is a strong at-will employment state with limited exceptions?", weight:1, critical:false, freeDetail:true, detail:"Florida is an at-will employment state. Employment may be terminated for any reason not prohibited by law. The main exceptions are discrimination (FCRA), retaliation (workers comp, whistleblower), and violation of public policy." },
    ]
  },
  IL: {
    name: "Illinois", code: "IL",
    tagline: "Prairie State Compliance Check",
    minWage: "$15.00/hr (2026)",
    updated: "2026-01-15",
    questions: [
      { id:"il1", cat:"wage", text:"Do you pay at least Illinois' minimum wage of $15.00/hour?", weight:3, critical:true, freeDetail:true, detail:"Illinois' minimum wage reached $15.00/hr as of January 2025. Chicago and Cook County have higher local minimums. The tipped minimum is 60% of the applicable minimum wage." },
      { id:"il2", cat:"wage", text:"Do you comply with the Illinois Day and Temporary Labor Services Act if using temp workers?", weight:2, critical:false, freeDetail:false, detail:"The Act requires temp agencies to pay temp workers equal pay and equivalent benefits as comparable direct-hire employees after 90 days on assignment. It also mandates specific notice requirements about pay, worksite conditions, and transportation." },
      { id:"il3", cat:"leave", text:"Do you provide paid leave for any reason (40 hours) under the Illinois Paid Leave for All Workers Act?", weight:3, critical:true, freeDetail:true, detail:"Effective January 2024, Illinois requires employers to provide 40 hours of paid leave per year that employees can use for any reason. Accrual is 1 hour per 40 hours worked. This is not limited to sick leave — employees can use it for any purpose without providing a reason." },
      { id:"il4", cat:"disc", text:"Do you comply with the Illinois Human Rights Act (covers employers with 1+ employees)?", weight:3, critical:true, freeDetail:false, detail:"The Illinois Human Rights Act applies to virtually all employers (1+ employees). It prohibits discrimination based on race, color, religion, sex, sexual orientation, gender identity, national origin, ancestry, age (40+), marital status, disability, military status, unfavorable discharge from military, citizenship status, arrest record, order of protection status, and work authorization status." },
      { id:"il5", cat:"disc", text:"Do you provide annual sexual harassment prevention training to all employees?", weight:2, critical:true, freeDetail:false, detail:"Illinois SB 75 requires all employers to provide sexual harassment prevention training annually. Restaurants and bars have additional requirements. Employers must also have a written sexual harassment policy." },
      { id:"il6", cat:"hire", text:"Do you comply with the Illinois AI Video Interview Act if using AI in hiring?", weight:2, critical:false, freeDetail:false, detail:"Illinois was the first state to regulate AI in hiring. The AI Video Interview Act requires employers to: notify applicants that AI is being used, explain how the AI works, and obtain consent before the interview. Applicants can request deletion of their video." },
      { id:"il7", cat:"term", text:"Do you pay final wages by the next regular payday following termination?", weight:2, critical:true, freeDetail:false, detail:"Illinois requires final compensation (including earned vacation) to be paid by the next regular payday. The Illinois Wage Payment and Collection Act provides strong remedies: employees can recover the amount owed plus 5% penalty per month, attorneys fees, and costs." },
      { id:"il8", cat:"hire", text:"Do you comply with the Illinois Equal Pay Act's ban on salary history inquiries?", weight:2, critical:false, freeDetail:false, detail:"Illinois prohibits employers from asking about salary history or using it to set compensation. Employers with 15+ employees must also include pay scale and benefits information in job postings." },
      { id:"il9", cat:"safety", text:"Do you carry workers compensation insurance (mandatory for all Illinois employers)?", weight:3, critical:true, freeDetail:false, detail:"Illinois requires workers compensation for all employers with even one employee. There are very few exceptions. Failure to carry coverage is a Class 4 felony. Officers and directors can be held personally liable." },
      { id:"il10", cat:"leave", text:"Do you comply with the Illinois Child Extended Bereavement Leave Act (250+ employees)?", weight:1, critical:false, freeDetail:false, detail:"Employers with 250+ employees must provide up to 12 weeks of unpaid leave for employees who experience the loss of a child by suicide or homicide. An additional 6 weeks is available for the loss of more than one child in a 12-month period." },
    ]
  },
  CO: {
    name: "Colorado", code: "CO",
    tagline: "Centennial State Compliance Check",
    minWage: "$14.81/hr (2026)",
    updated: "2026-01-15",
    questions: [
      { id:"co1", cat:"wage", text:"Do you pay at least Colorado's minimum wage of $14.81/hour (2026)?", weight:3, critical:true, freeDetail:true, detail:"Colorado's minimum wage is adjusted annually for inflation. The 2026 rate is $14.81/hr. The tipped minimum is $11.79/hr. Denver has a higher local minimum wage." },
      { id:"co2", cat:"wage", text:"Do you comply with the Colorado Overtime and Minimum Pay Standards (COMPS) Order?", weight:2, critical:true, freeDetail:false, detail:"The COMPS Order provides overtime protections for Colorado workers including daily overtime (12+ hours), meal period requirements (30 min for 5+ hour shifts), and 10-minute rest breaks per 4 hours. The COMPS Order covers most industries with some exemptions." },
      { id:"co3", cat:"hire", text:"Do you include pay ranges in all job postings under the Equal Pay for Equal Work Act?", weight:3, critical:true, freeDetail:true, detail:"Colorado was a pioneer in pay transparency. Employers must disclose hourly rate or salary range and a general description of benefits in all job postings for positions that could be performed in Colorado. This applies to remote positions that could be filled by Colorado residents. Non-compliance penalties up to $10,000 per violation." },
      { id:"co4", cat:"leave", text:"Do you provide Paid Family and Medical Leave Insurance (FAMLI) as required?", weight:3, critical:true, freeDetail:false, detail:"Colorado's FAMLI program provides up to 12 weeks (16 for pregnancy/childbirth complications) of paid leave for qualifying events. Premiums are split 50/50 between employer and employee at 0.9% of wages. All employers with 1+ employees must participate." },
      { id:"co5", cat:"leave", text:"Do you provide paid sick leave (48 hours minimum)?", weight:3, critical:true, freeDetail:false, detail:"Colorado's Healthy Families and Workplaces Act requires all employers to provide 48 hours of paid sick leave per year. Additional public health emergency leave (80 hours) may apply during declared emergencies." },
      { id:"co6", cat:"disc", text:"Do you comply with Colorado's anti-discrimination protections including sexual orientation and gender identity?", weight:3, critical:true, freeDetail:false, detail:"Colorado's Anti-Discrimination Act prohibits discrimination based on disability, race, creed, color, sex, sexual orientation, gender identity, religion, age (40+), national origin, ancestry, and marriage to a coworker. It applies to all employers." },
      { id:"co7", cat:"term", text:"Do you pay final wages immediately upon termination (or within 6 hours if payroll is closed)?", weight:3, critical:true, freeDetail:true, detail:"Colorado requires immediate payment of all earned wages upon termination. If the accounting department is closed, payment must be made within 6 hours of the start of the next business day. For employees who quit, wages are due by the next regular payday." },
      { id:"co8", cat:"hire", text:"Do you comply with the Colorado Chance to Compete Act (ban the box)?", weight:2, critical:false, freeDetail:false, detail:"Colorado prohibits employers with 11+ employees from asking about criminal history on initial job applications or advertising that applicants with criminal records will not be considered. Inquiries are only permitted after an initial interview or conditional offer." },
    ]
  },
  MA: {
    name: "Massachusetts", code: "MA",
    tagline: "Bay State Compliance Check",
    minWage: "$15.75/hr (2026)",
    updated: "2026-01-15",
    questions: [
      { id:"ma1", cat:"wage", text:"Do you pay at least Massachusetts' minimum wage of $15.75/hour (2026)?", weight:3, critical:true, freeDetail:true, detail:"Massachusetts minimum wage is $15.75/hr as of 2026. The tipped minimum is $7.15/hr. The state also requires time-and-a-half for Sunday and holiday work in retail, though this premium is being phased out." },
      { id:"ma2", cat:"wage", text:"Do you pay a Sunday/holiday premium for retail employees (at current phase-out rate)?", weight:2, critical:false, freeDetail:false, detail:"Massachusetts has been phasing out the Sunday and holiday premium pay requirement for retail. As of 2026, the premium is significantly reduced from the original time-and-a-half rate. Check current rates as this is being phased to zero." },
      { id:"ma3", cat:"leave", text:"Do you provide Paid Family and Medical Leave (PFML) through the state program?", weight:3, critical:true, freeDetail:true, detail:"Massachusetts PFML provides up to 26 weeks of combined family and medical leave per benefit year (12 weeks family, 20 weeks medical). Funded through payroll contributions (currently approximately 0.88% of wages, split between employer and employee for employers with 25+ covered individuals)." },
      { id:"ma4", cat:"leave", text:"Do you provide earned sick time (40 hours for 11+ employees, unpaid for smaller employers)?", weight:2, critical:true, freeDetail:false, detail:"Massachusetts requires employers with 11+ employees to provide 40 hours of paid earned sick time per year. Employers with fewer than 11 employees must provide 40 hours of unpaid sick time. Accrual is 1 hour per 30 hours worked." },
      { id:"ma5", cat:"hire", text:"Do you comply with the Massachusetts pay transparency law requiring pay ranges in job postings (25+ employees)?", weight:2, critical:true, freeDetail:false, detail:"Effective 2025, employers with 25+ employees must include pay range information in job postings and provide pay ranges upon request or when an employee is offered a new position. Employers with 100+ employees must submit EEO-type wage data reports." },
      { id:"ma6", cat:"disc", text:"Do you comply with Massachusetts anti-discrimination law (covers all employers)?", weight:3, critical:true, freeDetail:false, detail:"Massachusetts General Laws Chapter 151B covers all employers with 6+ employees and prohibits discrimination based on race, color, religion, national origin, sex, gender identity, sexual orientation, age (40+), disability, ancestry, military service, and genetic information." },
      { id:"ma7", cat:"term", text:"Do you pay discharged employees their final wages including unused vacation on the day of termination?", weight:3, critical:true, freeDetail:true, detail:"Massachusetts has one of the strictest final pay laws. Discharged employees must receive all wages including accrued unused vacation on the day of discharge. Employees who quit must be paid by the next regular payday. Treble damages are available for violations under the Wage Act." },
      { id:"ma8", cat:"disc", text:"Are you compliant with Massachusetts' restrictions on non-compete agreements?", weight:2, critical:false, freeDetail:false, detail:"Massachusetts restricts non-competes to 12 months maximum, requires garden leave pay (at least 50% of highest salary in last 2 years) or other mutually agreed consideration, and bans non-competes for non-exempt employees, hourly workers, and certain other categories." },
    ]
  },
  WA: {
    name: "Washington", code: "WA",
    tagline: "Evergreen State Compliance Check",
    minWage: "$16.66/hr (2026)",
    updated: "2026-01-15",
    questions: [
      { id:"wa1", cat:"wage", text:"Do you pay at least Washington's minimum wage of $16.66/hour (2026)?", weight:3, critical:true, freeDetail:true, detail:"Washington's minimum wage is adjusted annually based on CPI. The 2026 rate is approximately $16.66/hr. Seattle and other cities have higher local minimums (Seattle is over $20/hr for large employers). There is no tip credit in Washington." },
      { id:"wa2", cat:"wage", text:"Are you aware that Washington does not allow a tip credit against minimum wage?", weight:2, critical:true, freeDetail:true, detail:"Washington is one of the few states that does not allow employers to take a tip credit. Tipped employees must receive the full state minimum wage in addition to tips. This is a significant cost difference from federal rules." },
      { id:"wa3", cat:"leave", text:"Do you participate in Washington's Paid Family and Medical Leave (PFML) program?", weight:3, critical:true, freeDetail:false, detail:"Washington PFML provides up to 12 weeks of family leave, 12 weeks of medical leave, and up to 16 weeks combined per year. Premiums are approximately 0.92% of wages, with employer and employee sharing the cost. All employers with 1+ employees must participate." },
      { id:"wa4", cat:"leave", text:"Do you provide paid sick leave (1 hour per 40 hours worked)?", weight:3, critical:true, freeDetail:false, detail:"Washington requires all employers to provide paid sick leave accruing at 1 hour per 40 hours worked with no cap on accrual. Employees can use sick leave for their own or a family member's health condition, domestic violence, stalking, or closure of their child's school." },
      { id:"wa5", cat:"hire", text:"Do you include pay ranges in job postings (15+ employees)?", weight:2, critical:true, freeDetail:false, detail:"Washington's pay transparency law requires employers with 15+ employees to include wage scale or salary range and a general description of benefits in all job postings. This includes postings for remote work that could be performed from Washington." },
      { id:"wa6", cat:"disc", text:"Do you comply with the Washington Law Against Discrimination (WLAD)?", weight:3, critical:true, freeDetail:false, detail:"WLAD is one of the broadest anti-discrimination statutes in the US. It applies to employers with 8+ employees and protects against discrimination based on race, color, creed, national origin, sex, marital status, age (40+), disability, sexual orientation, gender identity, veteran/military status, and use of a trained guide dog." },
      { id:"wa7", cat:"term", text:"Do you pay final wages by the next regular payday?", weight:2, critical:true, freeDetail:false, detail:"Washington requires final wages to be paid by the end of the next regular pay period. There is no requirement for immediate payment upon termination but prompt payment is expected. Willful withholding can result in double damages." },
      { id:"wa8", cat:"disc", text:"Are you compliant with Washington's ban on non-compete agreements for employees earning under the salary threshold?", weight:2, critical:false, freeDetail:false, detail:"Washington restricts non-competes to employees earning over $120,559.99/year (adjusted annually). For independent contractors the threshold is over $301,399.98/year. Non-competes exceeding 18 months are presumed unreasonable." },
    ]
  },
  PA: {
    name: "Pennsylvania", code: "PA",
    tagline: "Keystone State Compliance Check",
    minWage: "$7.25 (federal)",
    updated: "2026-01-15",
    questions: [
      { id:"pa1", cat:"wage", text:"Are you aware that Pennsylvania's minimum wage is $7.25/hour (federal rate)?", weight:1, critical:false, freeDetail:true, detail:"Pennsylvania's minimum wage remains at $7.25/hr, matching the federal rate. Philadelphia has a higher minimum for city contractors ($16.20+) and some employers have voluntarily increased wages but there is no state-mandated increase above the federal level." },
      { id:"pa2", cat:"wage", text:"Do you pay overtime at 1.5x for hours over 40/week per Pennsylvania's Minimum Wage Act?", weight:3, critical:true, freeDetail:false, detail:"Pennsylvania's overtime rules generally follow FLSA but the state's Minimum Wage Act has some differences in exemption criteria. Pennsylvania also updated its overtime salary threshold regulations. Ensure proper classification under both federal and state rules." },
      { id:"pa3", cat:"leave", text:"If you are a Philadelphia employer with 10+ employees, do you provide paid sick leave?", weight:2, critical:false, freeDetail:false, detail:"While Pennsylvania has no statewide paid sick leave law, Philadelphia and Pittsburgh (Pittsburgh's enforcement has been limited) require paid sick leave. Philadelphia requires up to 40 hours for employers with 10+ employees and unpaid for smaller employers." },
      { id:"pa4", cat:"disc", text:"Do you comply with the Pennsylvania Human Relations Act (4+ employees)?", weight:3, critical:true, freeDetail:false, detail:"The PHRA applies to employers with 4+ employees and prohibits discrimination based on race, color, religious creed, ancestry, age (40+), sex, national origin, disability, familial status, and use of guide/support animals. Philadelphia and Pittsburgh have broader local protections covering sexual orientation and gender identity." },
      { id:"pa5", cat:"safety", text:"Do you carry workers compensation for all employees (mandatory in PA)?", weight:3, critical:true, freeDetail:true, detail:"Pennsylvania requires workers compensation for virtually all employees including part-time workers. There are very limited exceptions for some agricultural workers and domestic employees. Failure to carry coverage is a felony of the third degree with fines up to $15,000 and possible imprisonment." },
      { id:"pa6", cat:"term", text:"Do you pay final wages by the next regular payday?", weight:2, critical:true, freeDetail:false, detail:"Pennsylvania requires employers to pay all wages due by the next scheduled payday after separation. The Wage Payment and Collection Law allows employees to recover wages plus 25% liquidated damages plus attorneys fees." },
      { id:"pa7", cat:"hire", text:"Do you comply with Pennsylvania's ban on salary history inquiries (applicable in Philadelphia and Pittsburgh)?", weight:2, critical:false, freeDetail:false, detail:"While there is no statewide ban, Philadelphia prohibits employers from asking about salary history during the hiring process. Pittsburgh has a similar ordinance for city employees. State-level legislation has been proposed but not yet enacted." },
      { id:"pa8", cat:"hire", text:"Do you use E-Verify for public contracts (required for public works)?", weight:1, critical:false, freeDetail:false, detail:"Pennsylvania does not mandate E-Verify for all private employers but does require it for certain public works contracts under Act 127. Private employers can voluntarily participate." },
    ]
  },
  NJ: {
    name: "New Jersey", code: "NJ",
    tagline: "Garden State Compliance Check",
    minWage: "$16.00/hr (2026)",
    updated: "2026-01-15",
    questions: [
      { id:"nj1", cat:"wage", text:"Do you pay at least New Jersey's minimum wage of $16.00/hour (2026)?", weight:3, critical:true, freeDetail:true, detail:"New Jersey's minimum wage is $16.00/hr as of January 2026, with annual increases indexed to CPI going forward. Tipped employee minimum is $6.73/hr. Seasonal and small employer rates are lower but converging." },
      { id:"nj2", cat:"leave", text:"Do you provide earned sick leave (up to 40 hours per benefit year)?", weight:3, critical:true, freeDetail:true, detail:"New Jersey's Earned Sick Leave Law requires all employers to provide up to 40 hours of paid sick leave per year, accruing at 1 hour per 30 hours worked. Employers can frontload. Covers self-care, family care, school events, and domestic/sexual violence situations." },
      { id:"nj3", cat:"leave", text:"Do you comply with the New Jersey Family Leave Act (30+ employees) providing 12 weeks of job-protected leave?", weight:3, critical:true, freeDetail:false, detail:"The NJ FLA applies to employers with 30+ employees and provides 12 weeks of job-protected leave in a 24-month period for bonding with a new child or caring for a family member with a serious health condition. Combined with NJ's Temporary Disability and Family Leave Insurance, employees can receive partial wage replacement." },
      { id:"nj4", cat:"leave", text:"Do you participate in New Jersey's Family Leave Insurance and Temporary Disability Insurance programs?", weight:3, critical:true, freeDetail:false, detail:"NJ FLI provides up to 12 weeks of paid family leave benefits at 85% of average weekly wage (capped). TDI provides up to 26 weeks for the employee's own disability. Both are funded through payroll contributions. All covered employers must participate." },
      { id:"nj5", cat:"disc", text:"Do you comply with the NJ Law Against Discrimination (one of the broadest in the nation)?", weight:3, critical:true, freeDetail:false, detail:"The NJ LAD is one of the most expansive anti-discrimination statutes in the US. It applies to all employers regardless of size and protects against discrimination based on race, creed, color, national origin, nationality, ancestry, age, sex, pregnancy, gender identity/expression, disability, marital status, domestic partnership status, sexual orientation, genetic information, military service, and more." },
      { id:"nj6", cat:"hire", text:"Do you include pay ranges in job postings (10+ employees)?", weight:2, critical:true, freeDetail:false, detail:"Effective June 2025, New Jersey requires employers with 10+ employees to disclose the pay range and a general description of benefits in all job postings. This applies to internal and external postings and includes positions that can be performed remotely from New Jersey." },
      { id:"nj7", cat:"term", text:"Do you pay final wages by the next regular payday?", weight:2, critical:true, freeDetail:false, detail:"New Jersey requires all wages due to be paid by the next regular payday after termination. The NJ Wage Payment Law provides for up to 200% of wages owed as liquidated damages plus attorneys fees for non-payment." },
      { id:"nj8", cat:"term", text:"Are you aware of New Jersey's restrictions on non-compete agreements?", weight:2, critical:false, freeDetail:false, detail:"While New Jersey does not have a statutory ban on non-competes, courts apply strict scrutiny. Non-competes must be reasonable in scope, geography, and duration. They are unenforceable against employees terminated without cause in most circumstances, and recent legislative proposals would further restrict them." },
    ]
  },
};

export const CATEGORIES = [
  { id: "wage", title: "Wage & Hour", icon: "\u{1F4B0}" },
  { id: "hire", title: "Hiring & Onboarding", icon: "\u{1F4CB}" },
  { id: "leave", title: "Leave & Benefits", icon: "\u{1F3D6}" },
  { id: "safety", title: "Safety & Insurance", icon: "\u{1F6E1}" },
  { id: "disc", title: "Discrimination & Harassment", icon: "\u{2696}" },
  { id: "term", title: "Termination & Separation", icon: "\u{1F4E4}" },
];

export const ALL_STATES = [
  "AL","AK","AZ","AR","CA","CO","CT","DE","DC","FL","GA","HI","ID","IL","IN","IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY"
];

export const STATE_NAMES = {
  AL:"Alabama",AK:"Alaska",AZ:"Arizona",AR:"Arkansas",CA:"California",CO:"Colorado",CT:"Connecticut",DE:"Delaware",DC:"District of Columbia",FL:"Florida",GA:"Georgia",HI:"Hawaii",ID:"Idaho",IL:"Illinois",IN:"Indiana",IA:"Iowa",KS:"Kansas",KY:"Kentucky",LA:"Louisiana",ME:"Maine",MD:"Maryland",MA:"Massachusetts",MI:"Michigan",MN:"Minnesota",MS:"Mississippi",MO:"Missouri",MT:"Montana",NE:"Nebraska",NV:"Nevada",NH:"New Hampshire",NJ:"New Jersey",NM:"New Mexico",NY:"New York",NC:"North Carolina",ND:"North Dakota",OH:"Ohio",OK:"Oklahoma",OR:"Oregon",PA:"Pennsylvania",RI:"Rhode Island",SC:"South Carolina",SD:"South Dakota",TN:"Tennessee",TX:"Texas",UT:"Utah",VT:"Vermont",VA:"Virginia",WA:"Washington",WV:"West Virginia",WI:"Wisconsin",WY:"Wyoming"
};
